### ISSUE TITLE
Module should work with computed resources

### ISSUE THREAD

**Issue by soerenmartius** [mineiros-io/terraform-aws-route53#8]
We still need to support computed values. At the moment, the failover example is still failing.
Also mixing up non-alias and alias records is still not possible due to inconsistent maps.

Failing tests:

- Basic Routing
- Failover Routing

I've opened a new branch `fix-computed-values` that adds an s3 alias to the basic routing test. You can use that branch to proceed.

**Comment by mariux** [comment]
fixed in #12 please test again.
